#!/bin/bash 

# debug
# set -x

# check needed vars
if [[ -z $OPENSHIFT_REPO_DIR ]]; then
	echo "Error: OPENSHIFT_REPO_DIR not defined"
	return 1
fi

PLAY_PARAMS=""

PLAY_CONFIG_FILE="${OPENSHIFT_REPO_DIR}conf/openshift.conf"

if [[ -f $PLAY_CONFIG_FILE ]]; then

	function read_conf {
		local key=$1
		local default=$2
		local result=`grep "^$key[ |=]" $PLAY_CONFIG_FILE`

		# key not found
		if [[ -z "$result" ]]; then
			echo $default
		else
			result=`echo "$result" | grep -oP "=.*" | cut -b 1 --complement`
			echo $result
		fi
	}

	PLAY_PARAMS=$(read_conf "openshift.play.params" $PLAY_PARAMS)
fi

return 0