#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080 


# loads $PLAY_PARAMS
. ${OPENSHIFT_REPO_DIR}.openshift/action_hooks/load_config

if [[ ! $? -eq 0 ]]; then
	exit $?
fi

LOG_FILE="${OPENSHIFT_LOG_DIR}play.log"

export SBT_OPTS="-Dsbt.boot.directory=${OPENSHIFT_DATA_DIR}/project/target/boot -Dsbt.ivy.home=${OPENSHIFT_DATA_DIR}/project/target/repo"

cd ${OPENSHIFT_REPO_DIR}

./xsbt.sh clean start-script

chmod +x ${OPENSHIFT_REPO_DIR}target/start

export JAVA_OPTS="$PLAY_PARAMS "\
                 "-Dhttp.port=${OPENSHIFT_INTERNAL_PORT} "\
                 "-Dhttp.address=${OPENSHIFT_INTERNAL_IP} "\
                 "-Dconfig.resource=openshift.conf"

APP_COMMAND="${OPENSHIFT_REPO_DIR}target/start"

echo $JAVA_OPTS &>> $LOG_FILE
echo $APP_COMMAND &>> $LOG_FILE
nohup bash -c "${APP_COMMAND} &>> ${LOG_FILE} 2>&1" &> /dev/null &
