#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080 


if [[ ! $? -eq 0 ]]; then
	exit $?
fi

LOG_FILE="${OPENSHIFT_LOG_DIR}application.log"

export SBT_OPTS="-Dsbt.boot.directory=${OPENSHIFT_DATA_DIR}/project/target/boot -Dsbt.ivy.home=${OPENSHIFT_DATA_DIR}/project/target/repo"

cd ${OPENSHIFT_REPO_DIR}

function start_app {
  project=$1
  conf=$2
  export JAVA_OPTS="-Dhttp.port=${OPENSHIFT_INTERNAL_PORT} -Dhttp.address=${OPENSHIFT_INTERNAL_IP} -Dconfig.resource=${conf} -Dlogger.resource=logging.xml"
  APP_COMMAND="${OPENSHIFT_REPO_DIR}${project}target/start"
  echo $JAVA_OPTS &>> $LOG_FILE
  echo $APP_COMMAND &>> $LOG_FILE

  ./xsbt.sh clean ${project}start-script
  chmod +x ${APP_COMMAND}
  nohup bash -c "${APP_COMMAND} &>> ${LOG_FILE} 2>&1" &> /dev/null &
}

app_name=${OPENSHIFT_APP_NAME}
if [[ "${app_name}" =~ "renderer" ]]
then
  start_app renderer/ openshift-renderer.conf
else
  start_app "" openshift.conf
fi
