build:
  image: scalacenter/scastie-docker-sbt:0.13.13
  environment:
    - COURSIER_CACHE=/drone/.coursier
  commands:
    - export SBT_OPTS="-Xmx24G -XX:MaxPermSize=4G -Xss4M"
    - >
      sbt \
        -Dsbt.ivy.home=/drone/.ivy \
        -Djline.terminal=jline.UnsupportedTerminal \
        -Dsbt.log.noformat=true \
        continuousDelivery

cache:
  mount:
    - /drone/.ivy2
    - /drone/.coursier
