build:
  image: scalacenter/scastie-docker-sbt:0.0.7
  environment:
    - COURSIER_CACHE=/drone/.coursier
  commands:
    - export SBT_OPTS="-Xmx8G"
    - >
      time sbt \
        -Dsbt.ivy.home=/drone/.ivy \
        -Djline.terminal=jline.UnsupportedTerminal \
        -Dsbt.log.noformat=true \
        continuousDelivery

cache:
  mount:
    - /drone/.ivy2
    - /drone/.coursier
