pipeline:
  # Fetch folders from distributed cache
  sftp_cache_restore:
    image: plugins/sftp-cache
    restore: true
    mount:
      - /drone/.ivy2
      - /drone/.coursier-cache
      - /drone/.sbt
      - /drone/.git
    when:
      event: [push, pull_request, tag, deployment]

  tests:
    image: scalaplatform/scala:0.6
    pull: true
    environment:
      - COURSIER_CACHE=/drone/cache/coursier
    commands:
      - git fetch --tags && git log | head -n 20
      - ./bin/scalafmt --test
      - ./bin/copy_cache.sh /drone /root
      - /usr/bin/sbt $CI_TEST
      - ./bin/before_cache.sh
      - ./bin/copy_cache.sh /root /drone

  # Save folders in distributed cache
  sftp_cache_rebuild:
    image: plugins/sftp-cache
    rebuild: true
    mount:
      - /drone/.ivy2
      - /drone/.coursier-cache
      - /drone/.sbt
      - /drone/.git