build:
  image: scalacenter/scastie-docker-sbt:0.13.13
  environment:
    - COURSIER_CACHE=/drone/.coursier
  commands:
    - apk update
    - apk add nodejs
    - export SBT_OPTS="-Xmx24G -XX:MaxPermSize=4G -Xss4M"

    - sbt -Dsbt.ivy.home=/drone/.ivy continuousDelivery
cache:
  mount:
    - /drone/.ivy2
    - /drone/.coursier
