build:
  image: scalacenter/scastie-docker-sbt:0.0.9
  environment:
    - COURSIER_CACHE=/drone/cache/coursier
  commands:
    - test -d /drone/.sbt && cp -a /drone/.sbt /root
    - rm -rf /drone/.sbt
    - test -d /drone/.ivy2 && cp -a /drone/.ivy2 /root
    - rm -rf /drone/.ivy2

    - export SBT_OPTS="-Xmx8G -Djline.terminal=jline.UnsupportedTerminal -Dsbt.log.noformat=true"
    - time sbt drone

    - cp -a /root/.ivy2 /drone
    - cp -a /root/.sbt /drone

cache:
  mount:
    - /drone/.sbt
    - /drone/.ivy2
    - /drone/cache
