#!/bin/sh

. ~/.profile
unset GIT_DIR
export OPENSHIFT_INTERNAL_PORT=80
export SBT_OPTS="-Xmx312M -XX:MaxPermSize=80m"
cd ../scastie && git pull ../scastie-bare/ && authbind --deep ./test-openshift.sh