#!/bin/sh

. ~/.profile
unset GIT_DIR
export OPENSHIFT_INTERNAL_PORT=80
export SBT_OPTS="-server -Xmx152M -XX:MaxPermSize=60m"
cd ../scastie && git pull ../scastie-bare/ && authbind --deep ./test-openshift.sh