package org.scastie.client
package components

import org.scastie.api._
import japgolly.scalajs.react._

import vdom.all._

import org.scalajs.dom
import scala.scalajs.js

import org.scastie.client.i18n.I18n

final case class DownloadButton(snippetId: SnippetId, scalaTarget: ScalaTarget, code: String, language: String) {
  @inline def render: VdomElement = DownloadButton.component(this)
}

object DownloadButton {
  implicit val reusability: Reusability[DownloadButton] =
    Reusability.derive[DownloadButton]

  // Helper to build the scala-cli .scala file content
  def buildScalaCliFileContent(code: String): String = {
    val header = "// Generated by Scastie"
    // TODO: Include Scala-CLI prelude/imports if/when they are exposed in editor state
    if (code.trim.isEmpty) header + "\n"
    else header + "\n\n" + code
  }

  // Helper to trigger a browser download via Blob
  def triggerFileDownload(filename: String, content: String, contentType: String = "text/x-scala"): Unit = {
    // Create parts as BlobPart (String is accepted as a BlobPart)
    val parts = js.Array(content.asInstanceOf[dom.BlobPart])

    // BlobPropertyBag is a trait; construct via a dynamic literal and cast
    val opts = js.Dynamic.literal("type" -> contentType).asInstanceOf[dom.BlobPropertyBag]

    // Create the blob
    val blob = new dom.Blob(parts.asInstanceOf[js.Iterable[dom.BlobPart]], opts)

    val url = dom.URL.createObjectURL(blob)

    val a = dom.document.createElement("a").asInstanceOf[dom.html.Anchor]
    a.href = url
    a.download = filename
    dom.document.body.appendChild(a)
    a.click()
    a.remove()
    dom.URL.revokeObjectURL(url)
  }

  def render(props: DownloadButton): VdomElement = {
    val url = props.snippetId.url
    val fullUrl = s"/api/download/$url"

    val isScalaCliTarget = props.scalaTarget.targetType == ScalaTargetType.ScalaCli

    val onClickHandler: Callback =
      if (!isScalaCliTarget) Callback.empty
      else {
        // If snippet title/filename becomes available in editor state, prefer that here
        val filename = "scastie-snippet.scala"
        val content = buildScalaCliFileContent(props.code)
        Callback(triggerFileDownload(filename, content))
      }

    li(
      a(
        href := (if (isScalaCliTarget) "#" else fullUrl),
        // For scala-cli we download a single .scala file, keep .zip for others
        download := (if (isScalaCliTarget) "scastie-snippet.scala" else url.replaceAll("/", "-") + ".zip"),
        title := s"${I18n.t("editor.download")}",
        role := "button",
        cls := "btn",
        onClick ==> ((e: ReactMouseEvent) => {
          if (isScalaCliTarget) {
            e.preventDefault()
            onClickHandler
          } else Callback.empty
        })
      )(
        i(cls := "fa fa-download"),
        span(I18n.t("editor.download"))
      )
    )
  }

  private val component =
    ScalaComponent
      .builder[DownloadButton]("DownloadButton")
      .render_P(render)
      .configure(Reusability.shouldComponentUpdate)
      .build
}
