name: Bug Report
description: File a bug report
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## Bug report
  - type: input
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is
      placeholder: '...'
    validations:
      required: false
  - type: input
    id: scastie-link
    attributes:
      label: Scastie snippet link
      description: A link to the Scastie website
      placeholder: '...'
    validations:
      required: false
  - type: textarea
    id: to-reproduce
    attributes:
      label: To Reproduce
      description: Tell us the steps to reproduce the behavior
      placeholder: ...
      value: |
        1. Go to '...'
        2. Click on '...'
        3. See error
        ...
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
      placeholder: '...'
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: Screenshot ( Optional )
      description: Paste screenshot of the bug
      placeholder: '...'
    validations:
      required: false
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our Scastie are you running?
      options:
        - Scastie website
        - Embedded Scastie
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
